version: "3.1"
services:
  spring-app:
    image: library-management:latest
    container_name: spring-app
    environment:
      PROFILE: swagger
      MONGO_HOST: mongo
      RABBIT_HOST: rabbit
      REDIS_HOST: redis
    restart: always
    ports:
    - 7001:7001
    healthcheck:
      test: "exit 0"
    depends_on:
      - mongo
      - rabbit
      - redis

  mongo:
    image: mongo:4
    container_name: mongo
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: "exit 0"

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    restart: always
    ports:
    - 5672:5672
    - 15672:15672
    healthcheck:
      test: "exit 0"

  redis:
    image: redis:6
    command: redis-server --requirepass password
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: "exit 0"
