spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9090/mem:accountdb
    username: root
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none

  h2:
    console:
      enabled: true

  security:
    authentication:
      basic: false