server:
  port: 7007

app:
  security:
    url:
      password-login: /api/auth/login/default
      facebook-login: /api/auth/login/facebook

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:7000/eureka}

spring:
  application:
    name: LOG

  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        generate_statistics: true

  redis:
    host: localhost
    port: 6379
    password: password

  activemq:
    broker-url: tcp://localhost:61616
    user: root
    password: password
    queue:
      notifications: unprocessed-notifications
      mail: ready-to-process-notifications
    packages:
      trust-all: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: noreplylibrarymanagement@gmail.com
    password: "**library!"
    properties:
      mail:
        smtp:
          starttls:
            enable: true
    default-encoding: UTF-8

aspect:
  enabled:
    log-execution-time: true
    log-null-parameters: true

logging:
  level:
    com.sahin.library_management: debug
    org.springframework.data.mongodb.repository: debug
    org.springframework.data.mongodb.core.MongoTemplate: debug

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger/docs
    enabled: false

security:
  authentication:
    basic: false

amqp:
  enabled: true




