server:
  port: 7001

app:
  security:
    url:
      login: /api/auth/login
    jwt:
      privateKey: ssahin
      ttl: 3600

spring:
  jpa:
    show-sql: true


logging:
  level:
    com.sahin.library_management: debug