server:
  port: 7001

app:
  security:
    url:
      login: /api/auth/login
    jwt:
      privateKey: ssahin
      ttl: 3600

spring:
  jpa:
    show-sql: true

aspect:
  enabled:
    log-execution-time: true
    log-null-parameters: true

logging:
  level:
    com.sahin.library_management: debug

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger/docs
    enabled: false



