server:
  port: 7001

app:
  security:
    url:
      password-login: /api/auth/login
      facebook-login: /api/auth/facebook
    jwt:
      privateKey: ssahin
      ttl: 3600

spring:
  jpa:
    show-sql: true

  data:
    mongodb:
      port: 27017
      host: localhost
      username: root
      password: password
      authentication-database: admin
      database: logs

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

aspect:
  enabled:
    log-execution-time: true
    log-null-parameters: true

amqp:
  enabled: true

logging:
  level:
    com.sahin.library_management: debug
    org.springframework.data.mongodb.repository: debug

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger/docs
    enabled: false

security:
  authentication:
    basic: false



