server:
  port: 7001

app:
  security:
    url:
      password-login: /api/auth/login/default
      facebook-login: /api/auth/login/facebook
    jwt:
      privateKey: ssahin
      ttl: 3600

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        generate_statistics: true

  redis:
    host: localhost
    port: 6379
    password: password

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  activemq:
    broker-url: tcp://localhost:61616
    user: root
    password: password
    queue:
      name: unprocessed-notifications
    packages:
      trust-all: true

aspect:
  enabled:
    log-execution-time: true
    log-null-parameters: true

logging:
  level:
    com.sahin.library_management: debug
    org.springframework.data.mongodb.repository: debug
    org.springframework.data.mongodb.core.MongoTemplate: debug

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger/docs
    enabled: false

security:
  authentication:
    basic: false

amqp:
  enabled: true

feign:
  client:
    appName:
      library: libraryservice
      account: accountservice




