version: "3.1"
services:
  spring-app:
    image: library-management:latest
    container_name: spring-app
    environment:
      PROFILE: swagger
      RABBIT_HOST: rabbit
    restart: always
    ports:
    - 7001:7001
    healthcheck:
      test: "exit 0"
    depends_on:
      - rabbit

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    restart: always
    ports:
    - 5672:5672
    - 15672:15672
    healthcheck:
      test: "exit 0"
