spring:
  datasource:
    url: jdbc:h2:mem:librarydb;mode=MYSQL;INIT=CREATE SCHEMA IF NOT EXISTS LIBRARY_MANAGEMENT
    username: root
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none

  h2:
    console:
      enabled: true

amqp:
  enabled: false