server:
  port: 7004

app:
  security:
    url:
      password-login: /api/auth/login/default
      facebook-login: /api/auth/login/facebook
    jwt:
      privateKey: ssahin
      ttl: 3600

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:7000/eureka}

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        generate_statistics: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  redis:
    host: localhost
    port: 6379
    password: password

aspect:
  enabled:
    log-execution-time: true
    log-null-parameters: true

amqp:
  enabled: true

logging:
  level:
    com.sahin.library_management: debug

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger/docs
    enabled: false

security:
  authentication:
    basic: false



