server:
  port: 7002

app:
  security:
    url:
      password-login: /api/auth/login/default
      facebook-login: /api/auth/login/facebook
    jwt:
      privateKey: ssahin
      ttl: 3600

spring:
  application:
    name: ApiGateway
  jpa:
    show-sql: true
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        generate_statistics: true
  redis:
    host: localhost
    port: 6379
    password: password

logging:
  level:
    com.sahin.lms.apigw: debug

aspect:
  enabled:
    log-execution-time: true

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger/docs
    enabled: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7000/eureka


